docs_dir: docs
extra_css:
- css/custom.css
nav:
- Home: index.md
- Documentation:
  - Update from cloudmesh: README-update-from-cloudmesh.md
  - README: readme.md
  - User Guide: user.md
  - IO: io.md
  - Logging: logging.md
  - Stopwatch: stopwatch.md
  - System: sys.md
  - Telemetry: telemetry.md
  - Time: time.md
  - Aggregation: aggregation.md
- Project:
  - Changelog: CHANGELOG.md
  - GitHub: https://github.com/cloudmesh-ai/cloudmesh-ai-common
  - Issues: https://github.com/cloudmesh-ai/cloudmesh-ai-common/issues
  - Update: update.md
- API Reference: api.md

plugins:
  - cloudmesh-ai-theme
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table
            docstring_style: google
            group_by_category: true
            members: true
            separate_signature: true
            show_category_heading: true
            show_root_full_path: true
            show_source: true
            show_submodules: true
          paths:
          - src
site_name: Cloudmesh AI Common
theme:
  name: material
use_directory_urls: false
